### ISSUE TITLE
Migrate test suite to `tasty`

### ISSUE THREAD

**Issue by jkachmar** [hasura/graphql-parser-hs#85]
## TODO

- [x] add `tasty`, `tasty-hedgehog`, etc. as dependencies
- [x] convert existing tests to the new framework
- [x] use `tasty-discover` for automated test case discovery
- [x] make sure that test logic works as expected
  - `tasty` checks in parallel by default, so tests must not assume that they can be run sequentially

## Description

We use `hspec` in the monorepo but I _suspect_ we might benefit from using `tasty` as the test runner (in addition to `hspec`) since we’re using `tasty-bench` for automated benchmarks anyway.

At the very least this repo would be a convenient place to test the idea on a small scale, since the existing `hedgehog`-based test suite makes it a little inconvenient to add unit tests.

**Comment by i-am-tom** [comment]
Closed by #87

**Comment by jkachmar** [comment]
I obviously won’t be getting to any of these :)
